export type ProjectStatus = 'Live' | 'Completed' | 'Research Prototype' | 'In Development' | 'Open Source' | 'Private'
export type ProjectCategory = 'AI' | 'ML' | 'Computer Vision' | 'Full-Stack' | 'Research' | 'Browser Extension' | 'Trust & Safety' | 'Learning Technology'
export type EvidenceStatus = 'confirmed' | 'attributed' | 'inferred' | 'unknown'
export type ProjectClaim = { statement: string; status: EvidenceStatus; source?: string }
export type ProjectMetric = { label: string; value: string; context?: string }
export type Project = {
  key: string; slug: string; number: string; kicker: string; meta: string; title: string; summary: string
  problem: string; solution: string; built: string; evidence: string; stack: string
  status: ProjectStatus; featured: boolean; role: string; timeline: string; categories: ProjectCategory[]
  technologies: { name: string; category: string }[]; capabilities: string[]
  architecture: { title: string; description: string; nodes: string[] }
  metrics: ProjectMetric[]; claims: ProjectClaim[]; limitations: string[]
  links: { github?: string; live?: string; documentation?: string }
  presentationType: 'computer-vision' | 'research' | 'trust-system' | 'learning-system'
}

export const projects: Project[] = [
  { key:'dark-pattern', slug:'dark-pattern-hunter', number:'01', kicker:'Multimodal AI', meta:'Final year project · 2025—26', title:'Dark Pattern Hunter', summary:'A multimodal AI system for detecting deceptive e-commerce interfaces by combining browser observation with task-specific vision-language models.', problem:'Text-only detectors miss visual manipulation. Screenshots alone struggle to ground a finding to the exact interface element or behavior that caused it.', solution:'Combine screenshot, DOM, viewport, interaction, and temporal evidence before asking a local vision-language model to classify and explain a dark pattern.', built:'A Chrome extension, multi-viewport observation layer, screenshot + DOM evidence pipeline, AI-assisted dataset workflow, human verification tools, and QLoRA fine-tuning path for Qwen 3.5 4B.', evidence:'The verified dataset covers an 18-category taxonomy with COCO, YOLO, and JSONL export paths. Detections can be grounded back to real DOM elements for evidence highlighting.', stack:'Qwen 3.5 4B / 9B · QLoRA · Chrome Extension APIs · DOM analysis · browser automation', status:'Research Prototype', featured:true, role:'Solo developer · AI engineer · researcher', timeline:'2025—2026', categories:['AI','Computer Vision','Browser Extension','Research'], technologies:[{name:'Qwen 3.5',category:'Model'},{name:'QLoRA',category:'Fine-tuning'},{name:'Chrome Extension APIs',category:'Browser'},{name:'Python',category:'Pipeline'}], capabilities:['Multimodal detection','Dataset engineering','Browser intelligence','Human-in-the-loop review'], architecture:{title:'Browser evidence → VLM → grounded explanation',description:'The system observes the page at multiple levels, routes evidence through a local VLM, then anchors findings back to the interface.',nodes:['Browser','Extension','Evidence layer','Qwen VLM','Verification','Highlight']}, metrics:[{label:'Taxonomy',value:'18 categories',context:'Verified dark-pattern labels'},{label:'Model path',value:'Qwen 3.5 4B / 9B',context:'Local VLM inference and fine-tuning'}], claims:[{statement:'The system combines browser-level evidence with VLM reasoning.',status:'confirmed',source:'Supplied project specification'},{statement:'The dataset covers an 18-category taxonomy.',status:'confirmed',source:'Supplied project specification'}], limitations:['Research prototype; production-scale browser coverage is not claimed.'], links:{github:'https://github.com/EquityAviator/dark_pattern_hunter'}, presentationType:'computer-vision' },
  { key:'caption', slug:'caption-ai', number:'02', kicker:'ML research', meta:'Evidence-driven', title:'CaptionAI', summary:'An evidence-driven improvement search for local multimodal image captioning — from baseline diagnosis to a CLIP + GRPO serving champion.', problem:'The goal was not to pick a model from a leaderboard. It was to learn which changes survive fixed data, consumer compute, honest evaluation, and real serving constraints.', solution:'Run controlled experiments against a fixed evaluation protocol, keep changes only when evidence supports them, and carry the winning model into calibrated local serving.', built:'A fixed evaluation protocol, 10-generation experiment corpus, local training loop, hallucination audit, confidence calibration, OOD routing, FastAPI inference, and Next.js interface.', evidence:'Champion metrics: BLEU-1 0.6559, BLEU-4 0.1727, ROUGE-L 0.2782, CIDEr-D 0.5243, with a documented trade-off rather than a claim of universal improvement.', stack:'PyTorch · CLIP ViT-B/16 · Bahdanau attention · LSTM · GRPO · FastAPI · Next.js', status:'Research Prototype', featured:true, role:'Independent ML researcher · AI engineer', timeline:'2026', categories:['ML','Computer Vision','Research'], technologies:[{name:'CLIP ViT-B/16',category:'Vision encoder'},{name:'GRPO',category:'Optimization'},{name:'PyTorch',category:'Training'},{name:'FastAPI',category:'Serving'}], capabilities:['Experimental design','Multimodal learning','Model evaluation','Local inference'], architecture:{title:'Image → aligned features → decoder → calibrated serving',description:'A research loop connects controlled experiments to a local product surface without hiding trade-offs.',nodes:['Image','CLIP','Attention','LSTM + GRPO','Calibration','FastAPI']}, metrics:[{label:'BLEU-1',value:'0.6559',context:'+22.9% vs baseline'},{label:'BLEU-4',value:'0.1727',context:'+41.8% vs baseline'},{label:'Experiments',value:'10 / 20',context:'Major experiments / techniques audited'}], claims:[{statement:'The champion reached BLEU-1 0.6559.',status:'confirmed',source:'Supplied CaptionAI project specification'},{statement:'GRPO improved every reported metric.',status:'unknown',source:'Not supported; documented trade-offs exist'}], limitations:['The dataset and compute constraints limit generalization claims.'], links:{github:'https://github.com/EquityAviator'}, presentationType:'research' },
  { key:'chain', slug:'chainproof', number:'03', kicker:'AI product', meta:'Trust infrastructure', title:'ChainProof', summary:'A trust-focused review platform where AI moderation, human oversight, cryptographic sealing, public verification, and rewards share one workflow.', problem:'A published review is not automatically authentic, unchanged, or independently verifiable. The platform needed to handle suspicious content, moderation uncertainty, integrity, and auditability together.', solution:'Route reviews through AI analysis and deterministic policy, escalate uncertain cases to humans, then seal approved records for later public verification.', built:'A full-stack review platform with role-based dashboards, asynchronous moderation jobs, deterministic decision rules, append-only SHA-256 ledger, public verifier, photo evidence hashing, and analytics.', evidence:'AI failures route to MANUAL_REVIEW or FAIL rather than silently approving. The default implementation uses an internal append-only ledger, with an EVM adapter available for compatible deployments.', stack:'Next.js 16 · React 19 · Prisma · PostgreSQL / SQLite · AI provider abstraction · SHA-256 · Docker', status:'Completed', featured:true, role:'Solo developer · full-stack AI product engineer', timeline:'2026', categories:['AI','Full-Stack','Trust & Safety'], technologies:[{name:'Next.js',category:'Frontend'},{name:'Prisma',category:'Data'},{name:'SHA-256',category:'Integrity'},{name:'Docker',category:'Deployment'}], capabilities:['AI moderation','Human-in-the-loop workflows','Role-based systems','Cryptographic integrity'], architecture:{title:'Review → analysis → moderation → sealed record → verification',description:'The ledger proves record integrity; it does not claim that cryptography proves a review is truthful.',nodes:['Review','AI checks','Decision engine','Human review','Hash ledger','Verifier']}, metrics:[{label:'Workflow',value:'17 states',context:'Auditable review lifecycle'},{label:'AI policy',value:'Deterministic',context:'Model output does not directly set final state'}], claims:[{statement:'The default ledger is internal append-only SHA-256.',status:'confirmed',source:'Supplied ChainProof specification'},{statement:'Every review is stored on a public blockchain.',status:'unknown',source:'Not claimed; EVM adapter is available'}], limitations:['Public-chain deployment should not be assumed for every hosted review.'], links:{github:'https://github.com/EquityAviator'}, presentationType:'trust-system' },
  { key:'anglupol', slug:'anglupol', number:'04', kicker:'Learning technology', meta:'Production-oriented', title:'AngluPol', summary:'A personalized English–Polish learning platform built around one shared FSRS-4.5 learning engine and multiple replaceable activity modules.', problem:'Learning software needs to decide what to show, how to grade it, when it should return, and how teachers can understand progress without manually tracking every interaction.', solution:'Keep activities replaceable while centralizing grading events, FSRS scheduling, learning state, review logs, teacher tooling, and live monitoring.', built:'A sense-based vocabulary system, 13-stage data pipeline, shared ActivityModule contract, FSRS scheduler, teacher studio, private-link student access, and Socket.IO live classroom mirror.', evidence:'The current data pipeline reports 15,453 words, 15,641 senses, 1,160 taxonomy nodes, four learning activity types, and production-oriented Docker/PostgreSQL deployment tooling.', stack:'Next.js 16 · React 19 · TypeScript · FSRS-4.5 · Prisma · PostgreSQL · Socket.IO · Docker', status:'Completed', featured:true, role:'Solo developer · full-stack learning systems engineer', timeline:'2026', categories:['Full-Stack','Learning Technology'], technologies:[{name:'FSRS-4.5',category:'Learning engine'},{name:'Socket.IO',category:'Realtime'},{name:'PostgreSQL',category:'Data'},{name:'Docker',category:'Deployment'}], capabilities:['Adaptive learning','Realtime systems','Data pipelines','Teacher operations'], architecture:{title:'Activity modules → shared learning kernel → progress',description:'Four activities emit learning events into one result processor, keeping state progression consistent.',nodes:['Vocabulary','Activities','Events','FSRS','Learning state','Teacher mirror']}, metrics:[{label:'Vocabulary',value:'15,641 senses',context:'Pipeline-delivered sense records'},{label:'Activities',value:'4 modes',context:'Flashcards, memory, quiz, fill-in'}], claims:[{statement:'Activities feed a shared FSRS-4.5 engine.',status:'confirmed',source:'Supplied AngluPol specification'},{statement:'The platform is production-ready at broad commercial scale.',status:'unknown',source:'Scale is not established by supplied evidence'}], limitations:['Production-oriented describes the engineering posture, not commercial scale.'], links:{github:'https://github.com/EquityAviator'}, presentationType:'learning-system' },
]

export const experiments = [
  { label:'BASELINE', title:'DenseNet + LSTM', body:'A clean baseline made the actual bottlenecks visible: global pooling, vocabulary pressure, and overfitting.', metric:'0.5334', metricLabel:'BLEU-1 baseline' },
  { label:'DIAGNOSE', title:'Attention + BPE', body:'Spatial attention asked where the relevant information was; BPE reduced rare-word memorization.', metric:'0.5971', metricLabel:'BLEU-1 after controls' },
  { label:'SEARCH', title:'GRPO', body:'Reward optimization improved several quality and hallucination measures, while making trade-offs measurable.', metric:'0.6207', metricLabel:'BLEU-1 research run' },
  { label:'CURRENT CHAMPION', title:'CLIP + attention + LSTM + GRPO', body:'The gain came from a language-aligned feature space, not simply from a larger encoder. The final system reached BLEU-1 0.6559 while keeping hallucination auditing and calibrated local serving in the loop.', metric:'0.6559', metricLabel:'BLEU-1 score' },
]

export function getProject(slug: string) { return projects.find((project) => project.slug === slug) }
